services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db